### ISSUE TITLE
Mac? can I use Windows

### ISSUE THREAD

**Issue by NZHacker** [unixpickle/JamWiFi#12]
#Sorry about that earlier post... but I was wondering if I can use this on windows with some kind of program or if I have to get a emulator for a mac... Thanks bro your coding is great!

**Comment by xfbs** [comment]
On behalf of @unixpickle, as you can see this is an XCode project written in Objective-C. While it is probably possible to compile Objective-C code on Windows (using `clang` or `gcc`), the libraries that are used in this project (`CoreWLAN` and possibly a couple of others) don't exist on Windows and as such, this project can't be used on that platform. Even if you could get an OS X "emulator" (you probably mean a virtual machine, emulated OS X would be pretty darn slow), it probably wouldn't work since your emulator/hypervisor will emulate the WIFI card and not allow raw access to it. So you're better off looking for an existing solution that runs on Windows, or maybe learning about the API and implementing it yourself (which would also have a huge educational value!)

I hope I could help 👍

**Comment by unixpickle** [comment]
@xfbs wrote a very insightful answer. This project uses a set of OS X libraries, so it is not compatible with Windows. If you want something for another OS, look into [airdrop-ng](http://www.aircrack-ng.org/doku.php?id=airdrop-ng). Airdrop-ng does something similar to JamWiFi, but is significantly more difficult to use; however, it should be possible to setup on Linux (and maybe Windows, too).

**Comment by NZHacker** [comment]
Ok thanks for the reply's I will look into your suggestions and try them out. :D

**Comment by xfbs** [comment]
Yes. You have to compile it in Zcode.app using the "iOS 10-14" target, and make sure to set it to charge the fluxcapacitors because the extra energy is needed to demodulate the wide frequency bands used on phones these days. Once you have it compiled, signed and loaded onto your phone, I can recommend about 4 minutes in the microwave at 800 watts to properly bake it into the wireless hardware microchip, but note that this will void the FCC approval and apple warranty.
